import { describe, expect, test } from "vitest";
import {
	defineServer,
	generate,
	serverConfigurationSchema,
} from "../src/index.js";

describe("defineServer", () => {
	test("returns a ServerConfiguration instance with .generate()", () => {
		const cfg = defineServer({ hostname: "Test" });
		expect(cfg).toHaveProperty("generate");
		expect(typeof cfg.generate).toBe("function");
	});

	test("emits nothing when no fields are set", () => {
		const cfg = defineServer({});
		const lines = cfg.generate().split("\n");
		expect(lines[0]).toBe("# autogenerated by fivem-cfg");
		expect(lines).toHaveLength(1);
	});

	test("validates and rejects invalid data", () => {
		expect(() => defineServer({ maxClients: 9999 } as never)).toThrow();
	});
});

describe("generate output", () => {
	test("renders hostname", () => {
		const cfg = defineServer({ hostname: "My Server" });
		expect(cfg.generate()).toContain('set sv_hostname "My Server"');
	});

	test("renders maxClients", () => {
		const cfg = defineServer({ maxClients: 64 });
		expect(cfg.generate()).toContain('set sv_maxClients "64"');
	});

	test("renders oneSync when not default", () => {
		const cfg = defineServer({ oneSync: "legacy" });
		expect(cfg.generate()).toContain('set onesync "legacy"');
	});

	test("omits oneSync when not set", () => {
		const cfg = defineServer({});
		expect(cfg.generate()).not.toContain("onesync");
	});

	test("renders boolean true as string", () => {
		const cfg = defineServer({ appearAllowlisted: true });
		expect(cfg.generate()).toContain("true");
	});

	test("renders endpoint bindings", () => {
		const cfg = defineServer({
			endpoints: {
				udp: ["0.0.0.0:30120"],
				tcp: ["0.0.0.0:30120"],
			},
		});
		const output = cfg.generate();
		expect(output).toContain('endpoint_add_udp "0.0.0.0:30120"');
		expect(output).toContain('endpoint_add_tcp "0.0.0.0:30120"');
	});

	test("renders resources", () => {
		const cfg = defineServer({
			ensure: ["es_extended", "myrp"],
		});
		const output = cfg.generate();
		expect(output).toContain('ensure "es_extended"');
		expect(output).toContain('ensure "myrp"');
	});

	test("renders exec directives", () => {
		const cfg = defineServer({
			exec: ["extra.cfg"],
		});
		expect(cfg.generate()).toContain('exec "extra.cfg"');
	});

	test("renders ACE entries", () => {
		const cfg = defineServer({
			aces: [
				{
					principal: "identifier.steam:123",
					object: "command.kick",
					allow: true,
				},
			],
		});
		expect(cfg.generate()).toContain(
			'add_ace "identifier.steam:123" "command.kick" allow',
		);
	});

	test("renders licenseKey", () => {
		const cfg = defineServer({ licenseKey: "abc123" });
		expect(cfg.generate()).toContain('sv_licenseKey "abc123"');
	});

	test("renders rconPassword", () => {
		const cfg = defineServer({ rconPassword: "hunter2" });
		expect(cfg.generate()).toContain('rcon_password "hunter2"');
	});

	test("renders escape hatch set convars", () => {
		const cfg = defineServer({
			set: { sv_scriptHookAllowed: "1", sv_moo: "cow" },
		});
		const output = cfg.generate();
		expect(output).toContain('set "sv_scriptHookAllowed" "1"');
		expect(output).toContain('set "sv_moo" "cow"');
	});

	test("renders escape hatch sets convars", () => {
		const cfg = defineServer({
			sets: { tags: "roleplay, english", locale: "en-US" },
		});
		const output = cfg.generate();
		expect(output).toContain('sets "tags" "roleplay, english"');
		expect(output).toContain('sets "locale" "en-US"');
	});

	test("renders escape hatch setr convars", () => {
		const cfg = defineServer({
			setr: { sv_gameTime: "12:00" },
		});
		expect(cfg.generate()).toContain('setr "sv_gameTime" "12:00"');
	});
});

describe("generate standalone function", () => {
	test("takes raw ConfigData and produces server.cfg string", () => {
		const data = serverConfigurationSchema.parse({ hostname: "Test" });
		const output = generate(data);
		expect(output).toContain('set sv_hostname "Test"');
	});
});

describe("schema validation", () => {
	test("rejects out-of-range maxClients", () => {
		expect(() => serverConfigurationSchema.parse({ maxClients: 0 })).toThrow();
	});

	test("rejects invalid oneSync value", () => {
		expect(() =>
			serverConfigurationSchema.parse({ oneSync: "invalid" }),
		).toThrow();
	});

	test("accepts valid game build aliases", () => {
		const cfg = serverConfigurationSchema.parse({ enforceGameBuild: "h4" });
		expect(cfg.enforceGameBuild).toBe("h4");
	});

	test("accepts valid game build numbers", () => {
		const cfg = serverConfigurationSchema.parse({ enforceGameBuild: 3751 });
		expect(cfg.enforceGameBuild).toBe(3751);
	});
});
