import type { ServerConfigurationSchema } from "./schema";

const esc = (value: string): string => {
	if (/[\s"]/.test(value)) {
		return `"${value.replace(/"/g, '\\"')}"`;
	}
	return `"${value}"`;
};

const boolStr = (value: boolean): string => (value ? "true" : "false");

export const generate = (cfg: ServerConfigurationSchema): string => {
	const lines: string[] = ["# autogenerated by fivem-cfg"];

	if (cfg.licenseKey !== undefined) {
		lines.push(`sv_licenseKey ${esc(cfg.licenseKey)}`);
	}

	if (cfg.oneSync !== undefined) {
		lines.push(`set onesync ${esc(cfg.oneSync)}`);
	}

	// Identity & listing
	if (cfg.hostname !== undefined) {
		lines.push(`set sv_hostname ${esc(cfg.hostname)}`);
	}
	if (cfg.projectName !== undefined) {
		lines.push(`sets sv_projectName ${esc(cfg.projectName)}`);
	}
	if (cfg.projectDesc !== undefined) {
		lines.push(`sets sv_projectDesc ${esc(cfg.projectDesc)}`);
	}
	if (cfg.maxClients !== undefined) {
		lines.push(`set sv_maxClients ${esc(String(cfg.maxClients))}`);
	}
	if (cfg.master1 !== undefined) {
		lines.push(`set sv_master1 ${esc(cfg.master1)}`);
	}
	if (cfg.appearAllowlisted !== undefined) {
		lines.push(
			`set sv_appearAllowlisted ${esc(boolStr(cfg.appearAllowlisted))}`,
		);
	}
	if (cfg.allowlistInstructions !== undefined) {
		lines.push(
			`set sv_allowlistInstructions ${esc(cfg.allowlistInstructions)}`,
		);
	}
	if (cfg.endpointPrivacy !== undefined) {
		lines.push(`set sv_endpointPrivacy ${esc(boolStr(cfg.endpointPrivacy))}`);
	}
	// Game build
	if (cfg.enforceGameBuild !== undefined) {
		lines.push(`set sv_enforceGameBuild ${esc(String(cfg.enforceGameBuild))}`);
	}
	if (cfg.replaceExeToSwitchBuilds !== undefined) {
		lines.push(
			`set sv_replaceExeToSwitchBuilds ${esc(boolStr(cfg.replaceExeToSwitchBuilds))}`,
		);
	}

	// Auth & security
	if (cfg.authMaxVariance !== undefined) {
		lines.push(`set sv_authMaxVariance ${esc(String(cfg.authMaxVariance))}`);
	}
	if (cfg.authMinTrust !== undefined) {
		lines.push(`set sv_authMinTrust ${esc(String(cfg.authMinTrust))}`);
	}
	if (cfg.requestParanoia !== undefined) {
		lines.push(`set sv_requestParanoia ${esc(String(cfg.requestParanoia))}`);
	}
	if (cfg.filterRequestControl !== undefined) {
		lines.push(
			`set sv_filterRequestControl ${esc(String(cfg.filterRequestControl))}`,
		);
	}
	if (cfg.filterRequestControlSettleTimer !== undefined) {
		lines.push(
			`set sv_filterRequestControlSettleTimer ${esc(String(cfg.filterRequestControlSettleTimer))}`,
		);
	}
	if (cfg.pureLevel !== undefined) {
		lines.push(`set sv_pureLevel ${esc(String(cfg.pureLevel))}`);
	}
	// Networking
	if (cfg.enableNetworkedSounds !== undefined) {
		lines.push(
			`set sv_enableNetworkedSounds ${esc(boolStr(cfg.enableNetworkedSounds))}`,
		);
	}
	if (cfg.enableNetworkedPhoneExplosions !== undefined) {
		lines.push(
			`set sv_enableNetworkedPhoneExplosions ${esc(boolStr(cfg.enableNetworkedPhoneExplosions))}`,
		);
	}
	if (cfg.enableNetworkedScriptEntityStates !== undefined) {
		lines.push(
			`set sv_enableNetworkedScriptEntityStates ${esc(boolStr(cfg.enableNetworkedScriptEntityStates))}`,
		);
	}
	// Experimental
	if (cfg.experimentalStateBagsHandler !== undefined) {
		lines.push(
			`set sv_experimentalStateBagsHandler ${esc(boolStr(cfg.experimentalStateBagsHandler))}`,
		);
	}
	if (cfg.experimentalOnesyncPopulation !== undefined) {
		lines.push(
			`set sv_experimentalOnesyncPopulation ${esc(boolStr(cfg.experimentalOnesyncPopulation))}`,
		);
	}
	if (cfg.experimentalNetGameEventHandler !== undefined) {
		lines.push(
			`set sv_experimentalNetGameEventHandler ${esc(boolStr(cfg.experimentalNetGameEventHandler))}`,
		);
	}

	// File server
	if (cfg.httpFileServerProxyOnly !== undefined) {
		lines.push(
			`set sv_httpFileServerProxyOnly ${esc(boolStr(cfg.httpFileServerProxyOnly))}`,
		);
	}
	// Misc
	if (cfg.tebexSecret !== undefined) {
		lines.push(`sv_tebexSecret ${esc(cfg.tebexSecret)}`);
	}
	// Custom convars (escape hatches)
	if (cfg.set !== undefined) {
		for (const [key, value] of Object.entries(cfg.set)) {
			const str = String(value);
			lines.push(`set ${esc(key)} ${esc(str)}`);
		}
	}

	if (cfg.sets !== undefined) {
		for (const [key, value] of Object.entries(cfg.sets)) {
			lines.push(`sets ${esc(key)} ${esc(value)}`);
		}
	}

	if (cfg.setr !== undefined) {
		for (const [key, value] of Object.entries(cfg.setr)) {
			const str = String(value);
			lines.push(`setr ${esc(key)} ${esc(str)}`);
		}
	}

	// Credentials
	if (cfg.rconPassword !== undefined) {
		lines.push(`rcon_password ${esc(cfg.rconPassword)}`);
	}
	if (cfg.steamWebApiKey !== undefined) {
		lines.push(`set steam_webApiKey ${esc(cfg.steamWebApiKey)}`);
	}
	if (cfg.loadServerIcon !== undefined) {
		lines.push(`load_server_icon ${esc(cfg.loadServerIcon)}`);
	}

	// Network config
	if (cfg.netPort !== undefined) {
		lines.push(`netPort ${esc(String(cfg.netPort))}`);
	}
	if (cfg.netTcpConnLimit !== undefined) {
		lines.push(`net_tcpConnLimit ${esc(String(cfg.netTcpConnLimit))}`);
	}
	// Endpoints
	for (const endpoint of cfg.endpoints?.udp ?? []) {
		lines.push(`endpoint_add_udp ${esc(endpoint)}`);
	}
	for (const endpoint of cfg.endpoints?.tcp ?? []) {
		lines.push(`endpoint_add_tcp ${esc(endpoint)}`);
	}

	// Resources
	for (const resource of cfg.ensure ?? []) {
		lines.push(`ensure ${esc(resource)}`);
	}

	for (const resource of cfg.start ?? []) {
		lines.push(`start ${esc(resource)}`);
	}

	for (const resource of cfg.stop ?? []) {
		lines.push(`stop ${esc(resource)}`);
	}

	// Config files
	for (const file of cfg.exec ?? []) {
		lines.push(`exec ${esc(file)}`);
	}

	// Pool sizes
	for (const entry of cfg.increasePoolSize ?? []) {
		lines.push(`increase_pool_size ${esc(entry.poolName)} ${entry.increase}`);
	}

	// Event filters
	for (const event of cfg.blockNetGameEvents ?? []) {
		lines.push(`block_net_game_event ${esc(event)}`);
	}
	for (const event of cfg.unblockNetGameEvents ?? []) {
		lines.push(`unblock_net_game_event ${esc(event)}`);
	}
	for (const filter of cfg.channelFilters ?? []) {
		const cmd =
			(filter.remove ?? false)
				? "con_removeChannelFilter"
				: "con_addChannelFilter";
		lines.push(`${cmd} ${esc(filter.filter)} ${filter.action}`);
	}

	// ACE permissions
	for (const ace of cfg.aces ?? []) {
		lines.push(
			`add_ace ${esc(ace.principal)} ${esc(ace.object)} ${ace.allow ? "allow" : "deny"}`,
		);
	}
	for (const ace of cfg.removeAces ?? []) {
		lines.push(
			`remove_ace ${esc(ace.principal)} ${esc(ace.object)} ${ace.allow ? "allow" : "deny"}`,
		);
	}
	for (const entry of cfg.principals ?? []) {
		lines.push(`add_principal ${esc(entry.child)} ${esc(entry.parent)}`);
	}
	for (const entry of cfg.removePrincipals ?? []) {
		lines.push(`remove_principal ${esc(entry.child)} ${esc(entry.parent)}`);
	}
	for (const entry of cfg.testAces ?? []) {
		lines.push(`test_ace ${esc(entry.principal)} ${esc(entry.object)}`);
	}

	// Dev
	if (cfg.moo !== undefined) {
		lines.push("set moo 31337");
	}

	return lines.join("\n");
};
